### ISSUE TITLE
Undefined socketId in strategy-callback.middleware.ts

### ISSUE THREAD

**Issue by Fgerthoffert** [workfel/nest-auth#1]
Hi Johan,

I was playing with your repo as I'm trying to integrate a small REST API with Google OAuth2.

Just by cloning and configuring the google creds, I'm able to authenticate, but for some reason the `req.session.socketId` is undefined in the `strategy-callback.middleware.ts

# Steps to reproduce
 - Clone repo
 - Add credentials in config.ts
Add console statement to session-auth.middleware to 
```
...
      if (req.query.socketId) {
        console.log('SessionAuthMiddleware - socketId: ' + req.query.socketId);
        req.session.socketId = req.query.socketId;
      }
...
```
Add console statement to strategy-callback.middleware to
```
...
      const io = req.app.get('io');
      console.log(
        'StrategyCallbackMiddleware - socketId: ' + req.query.socketId,
      );

      const user = {
...
```
 - npm run start:dev

I get the following in the terminal:
```
[Nest] 50382   - 9/10/2019, 9:45:39 PM   [NestApplication] Nest application successfully started +1ms
SessionAuthMiddleware - socketId: 9MNB9C4fq3Kwrr3EAAAB
StrategyCallbackMiddleware - socketId: undefined
```

I'm being properly redirected to the oauth2 flow, StreategyCallbackMiddleware only shows up after logging-in.

Note: I'm using another front-end (a REACT app) to initiate the flow, but I don't think that makes a difference.

Thanks,
Francois

**Comment by workfel** [comment]
Hi, @Fgerthoffert  
You can show me your login front please  ?

**Comment by Fgerthoffert** [comment]
Sure, this would be this:

```typescript
import React, { FC } from 'react';
import io from 'socket.io-client';

import Button from '@material-ui/core/Button';

const LoginDialog: FC = () => {
  const socket = io('http://127.0.0.1:3001');

  const openPopup = () => {
    const url = `http://127.0.0.1:3001/auth/google?socketId=${socket.id}`;
    const width = 600;
    const height = 600;
    const left = window.innerWidth / 2 - width / 2;
    const top = window.innerHeight / 2 - height / 2;
    return window.open(
      url,
      '',
      `toolbar=no, location=no, directories=no, status=no, menubar=no, 
scrollbars=no, resizable=no, copyhistory=no, width=${width}, 
height=${height}, top=${top}, left=${left}`
    );
  };

  return (
        <Button onClick={openPopup} color='primary'>
          Open Log-in
        </Button>
  );
};

export default LoginDialog;

```
I did not add the piece where the UI is being sent back the details, but that shouldn't matter at this point since the API doesn't seem to know which socket id to use anyway :)

Thanks
